from dimagi.pages.views.core import (
    home,
    services,
    partners,
    covid_19,
    contact,
    proposals,
    awards,
    case_management,
    test_404,
    test_500,
    referral_commcare,
    update_referral_status,
    focus_placeholder,
)
