on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
      redis:
        image: redis
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
           python-version: 3.9.16

      - name: copy env variables
        run: |
          cp .travis.env .env
          curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
          echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee   /etc/apt/sources.list.d/yarn.list

      - name: Install Prerequisties 
        run: |
          sudo apt-get install curl -y
          sudo apt-get install yarn
          pip install pipenv
          pipenv install
          yarn install
              
      - name: Create test database
        run: |
          ps -ef | grep 5432 
          psql -c 'create database dimagidotcom_test;' -U postgres
        env:
          PGPASSWORD: postgres

      - name: Run tests
        run: |
            python manage.py migrate
            python manage.py test
            